"""users table

Revision ID: 7e353d472d52
Revises: e6275e440991
Create Date: 2018-05-14 23:24:18.885627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e353d472d52'
down_revision = 'e6275e440991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surrname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_surrname'), 'user', ['surrname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_surrname'), table_name='user')
    op.drop_column('user', 'surrname')
    # ### end Alembic commands ###
